apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-hw-service
  name: java-hw-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: java-hw-service
  type: NodePort
status:
  loadBalancer: {}
